#default_model: deepseek-chat
default_model: gpt-3.5-turbo

openai:
  "api_key": "sk-xxx"
  "base_url": "https://api.chatanywhere.tech/v1"
  "default_model": "gpt-3.5-turbo"

deepseek:
  api_key: sk-xxx
  base_url: https://api.deepseek.com
  default_model: deepseek-chat